# 元信息表
[meta]
title = "乱调一通酒"
author = "Air"
# 有多个作者时可以使用，两者仅需保留一行
version = "1.0.0"
license = "CC-BY-NC-SA 4.0"
date = 2025-04-01
update_date = 2025-04-01
desc = "乱调一通酒水，不保证这水能喝"

# 牌组表
[decks]
"调杯酒" = [
  "::10::{%__严茫熙拒绝}",
  "::1::{%__严茫熙接受}{%这是一杯严酒}"
  #"::8::{%__楼兰拒绝}",
  #"::3::{%__楼兰接受}",
  #"::4::{%__杨科拒绝}",
  #"::7::{%__杨科接受}",
  #"::1::{%__杜宇峰拒绝}",
  #"::10::{%__杜宇峰接受}"
]
"__严茫熙拒绝" = [
  "现在的招待人员是严茫熙。\n严茫熙手握着一支钢笔，趁你不注意的时候用力甩到了你的身旁，钉在了你身后的墙上。\n“下次可就不是这里了。”她拍了拍手，身上的棕黑色酒保服显得尤为宽松。",
  "现在的招待人员是严茫熙。\n严茫熙并没有回应你的要求，反而是用力拍了眼前的长桌，顿时，数个餐具从桌面上飞起发出了丁铃当啷的声音。\n“你找了个错误的时间。”你总感觉她的棕黑色酒保服有些宽松，大概是她还没准备好吧。",
  "现在的招待人员是严茫熙。\n严茫熙并没有搭理你，你倒是看到了她隐藏的手腕中藏着一条细微的火苗。\n你的潜意识告诉你，现在最好不要招惹眼前的这位女士。",
  "现在的招待人员是严茫熙。\n严茫熙从身边拿起了一把厨刀，用力抛向了你的方向。\n“在你身后。”你带着冷汗回过头去，那里赫然是一桶早已封装好的啤酒桶，看样子你只能试试这预制啤酒了。",
  "现在的招待人员是严茫熙。\n严茫熙手中的剪刀正散发着寒光，你似乎有一种错觉，这把剪刀刚刚才剪开某个人的嘴角。\n“需要做个美容手术？有助于饮食”她的声音依旧是如此冰冷，身着的棕黑色酒保服显得有些宽松。",
  "现在的招待人员是严茫熙。\n严茫熙正把玩着一把转轮手枪，随后便把枪口对准了你，扣动了扳机。\n“开玩笑的。”击锤声敲击着你的心脏，而罪魁祸首却只是淡淡的笑了笑，吹了吹毫无硝烟的枪口。",
  "现在的招待人员是严茫熙。\n严茫熙在和一个白发少年聊着天，完全忽视了你的存在。你有一种奇妙的感觉，你最好不要招惹眼前的两个人。",
  "现在的招待人员是严茫熙。\n严茫熙正默念着你所不了解的语言，只是一瞬，你仿佛看到了什么不可诉说的生物。\n“忘了有闲杂人员。”响指声回荡在你的耳旁，似乎大脑被抹除了什么，只剩视线搭在眼前的她。",
  "现在的招待人员是严茫熙。\n不过她现在不在这里，一个小小的告示牌写着“有事正忙”。",
  "现在的招待人员是严茫熙。\n“我们现在暂停营业，请稍后再来。”她正从柜台下掏出一个小告示牌，不过她看起来心情不错，或许是有什么要事要忙。"
]
"__严茫熙接受" = [
  "现在的招待人员是严茫熙。\n严茫熙手握着调酒杯，轻轻点了点头。“不接受点单，我做什么，你喝什么。”",
  "现在的招待人员是严茫熙。\n严茫熙擦了擦手边的调酒杯，啧了一声。“不接受点单，我做什么，你喝什么。”",
  "现在的招待人员是严茫熙。\n严茫熙摇晃着手中的调酒杯，杯子在她的肩膀上转了一圈后稳稳落在了她的手上。“不接受点单，我做什么，你喝什么。”",
  "现在的招待人员是严茫熙。\n严茫熙叹了口气，你能看到她把一个小牌子给收回到了柜台里。“不接受点单，我做什么，你喝什么。”",
  "现在的招待人员是严茫熙。\n严茫熙吹了一口气，整个调酒杯上泛起了红光。“不接受点单，我做什么，你喝什么。”"
]
"这是一杯严酒" = [
  "\n\n“这杯地腾飞达，采用了伏特加和橙子的组合，在陈化反应之后，所渲染出的颜色符合我们所热爱的大地，放心，在嘴里的绝对不是泥土味。”这杯酒水乍看起来像是从地里舀了一勺泥土一样，实际上严茫熙说的没错，这杯初入口中有一点淡淡的橙皮清香，混合上土豆的香气，微弱的酒精气息让这些本来有些淡雅的气味传入了你的鼻腔中。虽是在土地间扎稳了脚跟，但飘飘上头的奇妙意向确实能符合这杯酒水的名字。",
  "\n\n“我称这杯为自由飞翔，蓝色软饮在配合上独特的生命之水，插在酒杯旁的浅蓝色羽翼，让这杯酒试图飞向蓝天。”这杯带有些许梦幻感的浅蓝色渐变酒水给了你一种飘飘欲仙感，特别是气泡裹夹着高浓度的酒精在嘴中轻轻爆开，刺鼻的气味完全无法被舌头所阻拦，它冲进了你的鼻腔与胃袋中，仿佛置身于那广阔的天空一样。当然，仅仅是一口，你就感觉到了浓烈的醉意。",
  "\n\n“这杯可能会对初体验的人来说有些不易，别看整杯都像墨鱼吐出来的汁水，这里混合了强烈的香料以及特选干红，让这些物质产生了化学反应生成了黑，却又被迫结合在一起形成古怪的香味，我称之为枷锁。”酒水的颜色如同墨汁一样，吸收了所有的可见光线。这杯确实没有那么容易入口，舌尖的强烈刺激感不禁让你的身体出现了流泪的生理反应，但后味出现的芳香感充斥在口腔之中，每一口强烈的刺激配合上芳香让你感受到了这些搭配确实非常奇怪，也许可以再进一步得到提高。",
  "\n\n“一杯开胃酒，酸甜的口感适合每一位想要尝试饮料的小家伙。当然，葡萄的气味虽浓，但细细品尝或许能察觉出其中的涩口爽朗。”酒水的颜色呈现出神秘的紫罗兰色调，特别是在杯口上点缀了颗青提让这杯酒水的色调更显得奇妙。一口下肚，葡萄的清香在你的味蕾上跳动着，爽口的酒精溶解着葡萄的气息，酸酸甜甜的口感让你的精神都有些为之一振。",
  "\n\n“这杯可以让你灵感涌现，别看它的颜色像是苍白的枯枝一样，只要送入口中，大脑中的白质就会如同泉涌，让你奋笔疾书。”这杯灰白色的酒水隐隐散发着一股破败的气息，要不是它调制于眼前人的手中，你可能会怀疑这是从哪个垃圾堆整来的东西。不过严茫熙并没有骗你，虽然它的气味真的很刺鼻又古怪，但入口的轻轻苦感仿佛打通了你大脑与其他五感的链接，身体充满了活力。",
  "\n\n“经典款式，永恒的入门酒精饮品，注意别喝太多，你需要自己离开这里。”一杯淡黄色的啤酒端到了你的面前，气泡在液面中旋转跳跃，像是新鲜制作而成的酒水。入口和那些常见的啤酒几乎别无二致，不过你倒是能从中获取到麦芽香气以外的东西，仔细品尝，那或许是微微的芒果香气，和你眼前的她别无二致。",
  # 新增条目
  "\n\n“我管这叫‘赤焰’。用了些能点燃情绪的基酒，配上一点辛辣。别被它诱人的色泽骗了，这火焰能从舌尖烧进你的心底。”这杯酒呈现出一种深邃的宝石红色，在灯光下微微晃动时，边缘泛着诱人的光泽。初尝是短暂的甜意，像是某种莓果，但紧接着强烈的辛辣感如同火焰般在口腔中炸开，伴随着酒精带来的灼热感，瞬间扩散到全身，让你的血液似乎都沸腾了起来。",
  "\n\n“名字是‘静林低语’。采集了些林间的草本气息，如果你需要片刻安宁，或许可以试试。但别在里面迷失太久。”酒液是清澈的翠绿色，杯底似乎有微不可查的沉淀，如同林地覆盖的苔藓，杯壁上挂着几滴水珠，宛如晨露。入口清凉，带着浓郁而复杂的草本香气，有薄荷的清爽，也有类似松针或湿土的芬芳，后味带着一丝若有若无的苦涩，仿佛独自漫步在寂静森林深处，让人心绪沉静。",
  "\n\n“这杯，‘镜花水月’。看起来像杯清水，不是吗？滋味嘛，自己体会。眼睛看到的不一定是真的。”这杯酒几乎完全透明，只有在特定角度下才能看到一丝微光在液体中流转，显得格外纯净。闻起来也只有淡淡的、难以形容的清香。然而入口后，清冽的口感之下，隐藏着难以捉摸的复合味道，时而是淡雅的花香，时而是微弱的果酸，甚至带有一丝丝不易察觉的麻感，味道飘忽不定，如同雾中看花，难以把握。",
  "\n\n“试试这个，‘暖阳残梦’。融合了水果的甜和香料的暖，像午后打盹时的一个短暂好梦。醒来时或许会有点怅然若失。”这杯酒拥有温柔的蜜桃色泽，看起来温暖而诱人，表面或许还漂浮着一点点细微的香料碎末。喝下去，首先感受到的是柔和的甜味与成熟水果的馥郁芬芳，像是桃子或杏子，紧随其后的是肉桂或豆蔻带来的丝丝暖意，口感顺滑，仿佛被午后的阳光包裹。然而，回味中却带着一丝难以言喻的微酸与空虚感，正如梦醒后的那份失落。",
  "\n\n“一杯‘钢铁荆棘’。用烈度很高的谷物酒，加上一些带有锐利口感的植物提取物。味道很直接，就像它的名字。”酒液呈现出一种冷硬的银灰色，边缘锐利，看起来就不好惹。凑近能闻到强烈的酒精气息混合着某种类似金属和植物根茎的冷冽味道。入口是极其直接的冲击，高浓度酒精烧灼着喉咙，伴随着尖锐的苦涩和一丝草本的辛辣，没有任何缓冲，如同吞下了一根带刺的金属条，让人瞬间清醒，甚至有些刺痛。",
  "\n\n“名字叫‘遗忘之河’。用了些能让人放松的成分，颜色淡得像被稀释的记忆。喝完，或许能忘掉些不愉快的事，但也可能忘掉别的。”这杯酒是极浅的淡紫色，近乎于无色，在杯中轻轻晃动时，如同薄雾流动。气味也很寡淡，只有一点点类似薰衣草或某种安神草药的微弱香气。入口柔和，几乎感觉不到酒精的存在，只有一种温吞、模糊的甜意在舌尖蔓延，然后悄无声息地滑入喉咙。喝下后，确实感到一种放松和倦意，思绪也变得有些迟钝和模糊，仿佛真的有什么东西正在慢慢褪色。",
  "\n\n“这杯叫‘雷鸣骤雨’。捕捉了风暴来临前的气息，有点刺激，能让你精神一振，或者吓一跳。”酒体是浑浊的灰蓝色，隐约可见细小的银色颗粒在其中沉浮闪烁，如同暴雨将至的天空。闻起来有种雨后泥土混杂着臭氧的清新又略带刺激的气味。入口的瞬间是强烈的酸与麻，仿佛舌尖被微弱电流击中，紧接着是冰凉的液体带来的冲击感，回味中带着一丝矿物质般的凛冽，确实能让人瞬间清醒。",
  "\n\n“‘嬗变之液’。它的状态不稳定，味道和颜色可能在你喝的时候发生变化。祝你好运。”刚端上来时，这杯酒是温和的琥珀色，散发着淡淡的焦糖香。但当你晃动酒杯或准备入口时，颜色可能突然变得深邃或诡异，味道也随之改变——可能从甜变苦，从果香变草药味，甚至出现难以形容的味道。每一次尝试都可能不同，充满了不确定性与意外。",
  "\n\n“‘凝滞时光’。口感很厚重，流速缓慢。如果你想让时间慢下来，或许可以试试，但后果自负。”这杯酒呈现出几乎不透明的深棕黑色，质地极其粘稠，如同冷卻的糖浆或沥青，在杯壁上留下缓慢滑落的痕迹。气味是浓郁的甘草、黑巧克力和某种陈年木材的混合。入口感觉像是在吞咽某种半固体，口感厚重得几乎停滞在舌头上，甜味深沉而复杂，带着强烈的苦味和泥土气息，仿佛真的将时间都凝固在了这一口之中。",
  "\n\n“‘冰火交织’。用了些特殊的处理，让冷与热的感受能在口腔里同时出现。算是一种矛盾的体验。”外观上，这杯酒可能呈现出底部冰蓝顶部赤红的分层，或者在透明液体中悬浮着冷暖色调的晶体。入口的瞬间，舌尖首先感受到的是刺骨的冰凉，如同含着冰块，但随即喉咙深处和胃部却升腾起一股辛辣的暖流，冷热两种极端感受在口腔和食道中交替冲击，带来一种奇特而强烈的生理体验。",
  "\n\n“‘苦口良药’。别指望它好喝，这是用来清醒头脑，或者让你记住教训的。非常、非常苦。”颜色是深沉的墨绿色或浓黑褐色，散发着强烈的、类似中草药混合剂的刺鼻气味。入口的瞬间，难以言喻的强烈苦涩感会瞬间占领整个口腔，盖过一切其他味道，甚至可能让舌头短暂发麻。苦味持续很久，穿透力极强，喝完之后，整个世界似乎都变得清晰而锐利了，但也确实令人印象深刻。",
  "\n\n“‘昨日回响’。试图复现一些过去的风味，但记忆总会失真。或许你会尝到熟悉的东西，或许不会。”酒液呈现出一种淡淡的、略微发黄的陈旧色泽，像是老照片的颜色。闻起来有种混合了旧书页、香草、烤面包和一丝若有若无的花香的复杂气味。入口温和，带着一丝甜意和熟悉的味道——可能是童年某种糖果，或是祖母烘焙的糕点，但总感觉隔着一层薄纱，模糊不清，回味中带着淡淡的酸楚和挥之不去的怀旧感。",
  "\n\n“‘空无之境’。尽可能去除了所有强烈的风味和颜色，接近纯粹。感受它带来的虚无感吧。”这杯酒如同一杯纯水，清澈透明，毫无杂质，甚至连挂杯现象都不明显。闻起来几乎没有任何气味，或许只有一丝极其微弱的、类似矿泉水的清冷气息。入口顺滑，口感纯净，但当你仔细体会时，会发现它并非毫无味道，而是一种难以言述的“空”，一种极度淡漠的基底，喝下后仿佛一切感官都被暂时放空，带来一种奇异的平静或虚无。",
  "\n\n“‘熔炉之心’。灵感来自工业的心跳。有点金属味，有点烟火气，还有力量感。”酒液呈现出奇特的暗铜色或带有金属光泽的深灰色，在光线下转动时，仿佛有熔融的金属在流动。气味独特，混合了矿石、烟熏、机油（当然是可食用的模拟风味）和一丝焦糖的甜味。入口时，首先感受到的是一种微弱的金属涩感，紧接着是烟熏的焦香和酒精带来的灼热，口感粗砺而有力，仿佛吞下了一口工业时代的烈火与蒸汽。"
]