# 元信息表
[meta]
title = "随机枪械牌堆（含自用扩展）"
author = "Air"
# 有多个作者时可以使用，两者仅需保留一行
version = "1.0.3"
license = "CC-BY-NC-SA 4.0"
date = 2024-10-17
update_date = 2025-04-18
desc = "随机枪械牌堆，包含有作者主观评价与主观参数修正（普遍<常见<少见<稀有<罕见<古董）（便宜<大众<一般<较贵<昂贵<奢侈）\n目前只有随机手枪，如果不知道带啥手枪就来抽一发"

# 牌组表
[decks]
"随机手枪" = [
  """\
  鲁格 Mark.22自动手枪
  年代：1950年起至今
  技能：射击（手枪） 子弹：.22lr
  伤害：1D6 载弹量：10
  射程：10码 每轮攻击次数：1(3)
  故障值：100 价格：大众
  常见程度（KP允许程度）：常见
  有史以来最好的.22自动手枪，除了外形酷炫，极高的精准度也让射手爱不释手，可以使用简单的配件进行搭配，提高上手的命中率。
  特殊弹药：曳光弹，为下一次的射击提供+5的成功率加成。
  """,
  """\
  气动射钉枪（火药射钉枪）
  年代：1965年起（20世纪初）
  技能：射击（手枪） 子弹：钉子
  伤害：1D2(1D4) 载弹量：50
  射程：1码(5码) 每轮攻击次数：1(3)
  故障值：99 价格：便宜(大众)
  常见程度（KP允许程度）：普遍(常见)
  可以作为临时远程武器使用，甚至可以在国内获取到这个东西，射程属于能用就行的范畴。
  """,
  """\
  4.5mm BB弹手枪
  年代：20世纪初
  技能：射击（手枪） 子弹：4.5mm BB弹
  伤害：1D3 载弹量：20
  射程：10码 每轮攻击次数：1
  故障值：99 价格：便宜
  常见程度（KP允许程度）：普遍
  奥运赛场所用的子弹，能够保证在10M以内的精度，国内亦可获取，但需要进行登记管控。
  """,
  """\
  勃朗宁M1906袖珍手枪
  年代：1906年
  技能：射击（手枪） 子弹：.25 ACP
  伤害：1D6 载弹量：6
  射程：8码 每轮攻击次数：1(3)
  故障值：99 价格：便宜
  常见程度（KP允许程度）：常见
  非常小巧的一支手枪，总重不超过一斤，俗称掌心雷，但过于迷你也导致了该手枪难以瞄准敌人。
  """,
  """\
  LWS-25手枪
  年代：1981年
  技能：射击（手枪） 子弹：.25 ACP
  伤害：1D6 载弹量：6
  射程：10码 每轮攻击次数：1(3)
  故障值：99 价格：便宜
  常见程度（KP允许程度）：常见
  非常小巧的一支手枪，.25ACP手枪的现代化版本，进行了一些缺点改进以让射击手感略有提升。
  特殊：该手枪只可打空尖弹，对无甲目标伤害+1，有甲目标伤害减半。
  """,
  """\
  毛瑟C96手枪
  年代：1896年
  技能：射击（手枪） 子弹：.30 Mauser
  伤害：1D8 载弹量：10
  射程：15码 每轮攻击次数：1(3)
  故障值：98 价格：大众
  常见程度（KP允许程度）：常见
  俗称盒子炮，19世纪末少见的半自动手枪，由于跳动的后坐力较大，需要射手有一定的射击水平。
  """,
  """\
  TT-33托卡列夫手枪
  年代：1933年
  技能：射击（手枪） 子弹：7.62托卡列夫手枪弹/.30 Mauser
  伤害：1D8 载弹量：8
  射程：15码 每轮攻击次数：1(3)
  故障值：99 价格：大众
  常见程度（KP允许程度）：常见
  将1911手枪简练化设计而出的手枪，精准高效，可发射当年常见的手枪弹药。
  """,
  """\
  FN M1900半自动手枪
  年代：1900年
  技能：射击（手枪） 子弹：.32 ACP
  伤害：1D8 载弹量：7
  射程：15码 每轮攻击次数：1(3)
  故障值：99 价格：大众
  常见程度（KP允许程度）：常见
  早期套筒式半自动手枪，与现代化的手枪结构不太类似，没有外露的击锤使得该枪在掏出的时候不易挂上衣物。
  """,
  """\
  瓦尔特PPK手枪
  年代：1908年
  技能：射击（手枪） 子弹：.32 ACP
  伤害：1D8 载弹量：7
  射程：12码 每轮攻击次数：1(3)
  故障值：99 价格：大众
  常见程度（KP允许程度）：常见
  德国产著名杀死希特勒的手枪，采用了创造性的双动结构与多重保险，使得该枪小巧，经久不衰。
  """,
  """\
  Kel-Tec P-32手枪
  年代：1999年
  技能：射击（手枪） 子弹：.32 ACP
  伤害：1D8 载弹量：7
  射程：12码 每轮攻击次数：1(3)
  故障值：99 价格：大众
  常见程度（KP允许程度）：常见
  现代化无外露击锤的袖珍手枪，针对民用市场进行投入，总重低至266g。
  """,
  """\
  生命卡.22 WMR手枪
  年代：2017年
  技能：射击（手枪） 子弹：.22 WMR
  伤害：1D8 载弹量：1
  射程：8码 每轮攻击次数：1
  故障值：100 价格：大众
  常见程度（KP允许程度）：常见
  如同信用卡一般的折叠手枪，发射的子弹不容小觑，卡槽可以携带三枚备用子弹。
  """,
  """\
  SW M1903转轮手枪
  年代：1903年
  技能：射击（手枪） 子弹：.32 ACP
  伤害：1D8 载弹量：6
  射程：15码 每轮攻击次数：1(3)
  故障值：100 价格：大众
  常见程度（KP允许程度）：少见
  早期SW的转轮手枪，采用.32ACP子弹。装填需两回合。
  """,
  """\
  FN M1903半自动手枪
  年代：1903年
  技能：射击（手枪） 子弹：.380 ACP
  伤害：1D8+1 载弹量：8
  射程：15码 每轮攻击次数：1(3)
  故障值：99 价格：大众
  常见程度（KP允许程度）：常见
  基于1900手枪改进而来，采用了威力更大的.380ACP子弹，为后续的半自动手枪提供了模板。
  """,
  """\
  韦伯利转轮手枪
  年代：1901年起
  技能：射击（手枪） 子弹：.38 ACP
  伤害：1D10 载弹量：6
  射程：15码 每轮攻击次数：1(3)
  故障值：100 价格：大众
  常见程度（KP允许程度）：常见
  英国产转轮手枪，可搭配刺刀等配件，采用中折式方式打开弹巢进行装填。（无装填器需两回合装填）
  """,
  """\
  贝雷塔Pico手枪
  年代：2013年
  技能：射击（手枪） 子弹：.380 ACP
  伤害：1D8+1 载弹量：6
  射程：12码 每轮攻击次数：1(3)
  故障值：100 价格：大众
  常见程度（KP允许程度）：常见
  意大利产小巧隐蔽手枪，相较于IPhone6要更短，空枪重仅326g。
  """,
  """\
  M1911政府型手枪
  年代：1929年
  技能：射击（手枪） 子弹：.38 Super
  伤害：1D10+1 载弹量：9
  射程：15码 每轮攻击次数：1(3)
  故障值：99 价格：大众
  常见程度（KP允许程度）：少见
  大威力手枪，虽然仅在几年后，子弹便被.357 Magnum所取代。
  """,
  """\
  柯尔特M1911手枪
  年代：1911年
  技能：射击（手枪） 子弹：.45 ACP
  伤害：1D10+2 载弹量：7
  射程：15码 每轮攻击次数：1(3)
  故障值：99 价格：大众
  常见程度（KP允许程度）：常见
  经久不衰的典范，美国的历史里程碑，著名的半自动手枪。
  """,
  """\
  IMI .357口径沙漠之鹰
  年代：1983年
  技能：射击（手枪） 子弹：.357 Magnum
  伤害：1D8+1D4 载弹量：9
  射程：15码 每轮攻击次数：1(3)
  故障值：96 价格：一般
  常见程度（KP允许程度）：少见
  大威力马格南手枪，但厚重的握把注定了这把沙漠之鹰并不适合用于作战。
  """,
  """\
  IMI .44口径沙漠之鹰
  年代：1983年
  技能：射击（手枪） 子弹：.44 Magnum
  伤害：1D10+1D4+2 载弹量：8
  射程：15码 每轮攻击次数：1(3)
  故障值：95 价格：一般
  常见程度（KP允许程度）：少见
  大威力马格南手枪，但厚重的握把注定了这把沙漠之鹰并不适合用于作战。
  """,
  """\
  IMI .50口径沙漠之鹰
  年代：1983年
  技能：射击（手枪） 子弹：.50 AE
  伤害：1D10+1D6+3 载弹量：7
  射程：15码 每轮攻击次数：1(3)
  故障值：94 价格：一般
  常见程度（KP允许程度）：少见
  大威力马格南手枪，但厚重的握把注定了这把沙漠之鹰并不适合用于作战。
  """,
  """\
  柯尔特Python蟒蛇左轮手枪
  年代：1955年
  技能：射击（手枪） 子弹：.357 Magnum
  伤害：1D8+1D4 载弹量：6
  射程：15码 每轮攻击次数：1(3)
  故障值：100 价格：较贵
  常见程度（KP允许程度）：常见
  大威力左轮手枪，能够更加容易扣动扳机发射弹药，一度吸引了警察进行使用。
  """,
  """\
  S&W M29左轮手枪
  年代：1955年
  技能：射击（手枪） 子弹：.44 Magnum
  伤害：1D10+1D4+2 载弹量：6
  射程：15码 每轮攻击次数：1(3)
  故障值：100 价格：一般
  常见程度（KP允许程度）：常见
  大威力左轮手枪，后坐力较大，更加适合用作狩猎用途，后续生产的防滑握把型号能避免出现脱手的尴尬情况。
  """,
  """\
  S&W 4006型手枪
  年代：1990年
  技能：射击（手枪） 子弹：.40 S&W
  伤害：1D10 载弹量：11
  射程：15码 每轮攻击次数：1(3)
  故障值：97 价格：一般
  常见程度（KP允许程度）：常见
  在经历了迈阿密惨案后所推行的新子弹，相较于9mm子弹弹道更加稳定。但容易产生膛炸的情况。
  """,
  """\
  Glock17手枪
  年代：1983年
  技能：射击（手枪） 子弹：9mm手枪弹
  伤害：1D10 载弹量：17
  射程：15码 每轮攻击次数：1(3)
  故障值：99 价格：一般
  常见程度（KP允许程度）：常见
  经典9mm半自动手枪，轻便可靠耐用，但可能会出现弱腕导致卡壳。
  """,
  """\
  Glock26手枪
  年代：1996年
  技能：射击（手枪） 子弹：9mm手枪弹
  伤害：1D10 载弹量：10
  射程：10码 每轮攻击次数：1(3)
  故障值：98 价格：一般
  常见程度（KP允许程度）：常见
  Glock手枪中最小的型号，方便隐秘携带，牺牲了后坐力以及握姿舒适度。
  """,
  """\
  Glock20手枪
  年代：1990年
  技能：射击（手枪） 子弹：10mm手枪弹
  伤害：1D10+1 载弹量：15
  射程：15码 每轮攻击次数：1(3)
  故障值：98 价格：一般
  常见程度（KP允许程度）：少见
  10mm口径Glock，应对火力不足的情况，双排供弹导致握把较厚，以及较大的后坐力使得射手需要有相应的经验。
  """,
  """\
  Glock22手枪
  年代：1990年
  技能：射击（手枪） 子弹：.40 S&W
  伤害：1D10 载弹量：15
  射程：15码 每轮攻击次数：1(3)
  故障值：97 价格：一般
  常见程度（KP允许程度）：常见
  10mm子弹改进型号，略微降低了口径以让射手能够更加有效掌握该枪械，.40子弹容易产生膛炸的情况。
  """,
  """\
  Glock22手枪
  年代：1990年
  技能：射击（手枪） 子弹：.40 S&W
  伤害：1D10 载弹量：15
  射程：15码 每轮攻击次数：1(3)
  故障值：97 价格：一般
  常见程度（KP允许程度）：常见
  10mm子弹改进型号，略微降低了口径以让射手能够更加有效掌握该枪械，.40子弹容易产生膛炸的情况。
  """,
  """\
  伯莱塔M9手枪
  年代：1985年
  技能：射击（手枪） 子弹：9mm手枪弹
  伤害：1D10 载弹量：15
  射程：15码 每轮攻击次数：1(3)
  故障值：99 价格：一般
  常见程度（KP允许程度）：常见
  曾经的军用手枪，可靠，耐用，重量轻便，容易修理，但弹匣容易出现弹簧力不足的情况，导致卡壳。
  """,
  """\
  西格绍尔P228手枪
  年代：1988年
  技能：射击（手枪） 子弹：9mm手枪弹
  伤害：1D10 载弹量：13
  射程：15码 每轮攻击次数：1(3)
  故障值：99 价格：一般
  常见程度（KP允许程度）：常见
  人体工学非常好的紧凑手枪，无论手掌大小如何都能轻松使用。
  """,
  """\
  西格绍尔P229手枪
  年代：1992年
  技能：射击（手枪） 子弹：.357 SIG
  伤害：1D10 载弹量：12
  射程：15码 每轮攻击次数：1(3)
  故障值：99 价格：一般
  常见程度（KP允许程度）：少见
  采用了西格绍尔自研的.357 Sig弹，但由于效果与9mm不相上下，使得该枪竞争力薄弱。
  """,
  """\
  伯莱塔93R手枪
  年代：1975年
  技能：射击（手枪） 子弹：9mm手枪弹
  伤害：1D10 载弹量：12
  射程：15码 每轮攻击次数：1 or 3
  故障值：95 价格：一般
  常见程度（KP允许程度）：稀有
  可三连发的自动手枪，但由于只适合近距离作战，并没有被执法部门大量采用。
  """,
  """\
  Glock18C手枪
  年代：1983年
  技能：射击（手枪） 子弹：9mm手枪弹
  伤害：1D10 载弹量：17 or 33
  射程：15码 每轮攻击次数：1(3) or 全自动
  故障值：92 价格：较贵
  常见程度（KP允许程度）：罕见
  射速极快的自动手枪，非常难以进行掌控。
  """,
  """\
  斯捷奇金APS冲锋手枪
  年代：1951年
  技能：射击（手枪） 子弹：9x18mm马卡洛夫手枪弹
  伤害：1D8+1 载弹量：20
  射程：15码 每轮攻击次数：1(3) or 全自动
  故障值：99 价格：一般
  常见程度（KP允许程度）：罕见
  苏联产自动手枪，通过降射速来让后坐力保持在可观的位置，精准，便宜，好用，因枪托过于笨重而远离主要军队部署。
  """,
  """\
  马卡洛夫手枪
  年代：1951年
  技能：射击（手枪） 子弹：9x18mm马卡洛夫手枪弹
  伤害：1D8+1 载弹量：8
  射程：15码 每轮攻击次数：1(3)
  故障值：99 价格：便宜
  常见程度（KP允许程度）：常见
  苏联产半自动手枪，因为威力较低以及弹容量低被逐步淘汰军队服役。
  """,
  """\
  GSh-18手枪
  年代：1990年
  技能：射击（手枪） 子弹：9mm手枪弹
  伤害：1D10 载弹量：18
  射程：15码 每轮攻击次数：1(3)
  故障值：99 价格：一般
  常见程度（KP允许程度）：常见
  俄罗斯产半自动手枪，取代了上个世纪的马卡洛夫手枪，可靠轻便，威力更大，至今仍在服役。
  """,
  """\
  MP-443乌鸦手枪
  年代：2000年
  技能：射击（手枪） 子弹：9mm手枪弹
  伤害：1D10 载弹量：18
  射程：15码 每轮攻击次数：1(3)
  故障值：98 价格：一般
  常见程度（KP允许程度）：常见
  俄罗斯产半自动手枪，采用了全钢设计使得该手枪有些压手，握把坚固，但手枪缺乏装配配件的空间。
  """,
  """\
  柯尔特M1873转轮手枪
  年代：1873年
  技能：射击（手枪） 子弹：.45 Colt
  伤害：1D10+2 载弹量：6
  射程：15码 每轮攻击次数：1(3)
  故障值：100 价格：一般
  常见程度（KP允许程度）：常见
  美国产经典转轮手枪，西部牛仔常用枪械，曾在现代再度风靡一段时间，装填完整弹仓需两回合。
  """,
  """\
  夏普斯胡椒瓶手枪
  年代：1859年
  技能：射击（手枪） 子弹：.22 Short
  伤害：1D4 载弹量：4
  射程：5码 每轮攻击次数：1(3)
  故障值：99 价格：一般
  常见程度（KP允许程度）：常见
  袖珍德林杰手枪，非常适合藏在口袋里给匪徒进行还击，威力过小且难以瞄准是该手枪的最大痛点，换弹需抛弃手枪中的剩余子弹。
  """,
  """\
  柯尔特M1835转轮手枪
  年代：1835年
  技能：射击（手枪） 子弹：柯尔特纸壳弹
  伤害：1D8 载弹量：6
  射程：15码 每轮攻击次数：1(3)
  故障值：98 价格：一般
  常见程度（KP允许程度）：常见
  第一支转轮手枪，容易走火，火药容易泄露，但这是里程碑意义的手枪，一回合装弹1发。
  """,
  """\
  纳甘M1895转轮手枪
  年代：1895年
  技能：射击（手枪） 子弹：7.62mm纳甘弹
  伤害：1D8+1 载弹量：7
  射程：15码 每轮攻击次数：1(3)
  故障值：100 价格：一般
  常见程度（KP允许程度）：常见
  苏联转轮手枪，有单动和双动版本，采用了埋头弹以及转轮手枪罕见的封闭设计，使得该枪可以装配消音器。一回合装弹1发。
  """,
  """\
  西格P320手枪
  年代：2018年
  技能：射击（手枪） 子弹：9mm手枪弹
  伤害：1D10 载弹量：17
  射程：15码 每轮攻击次数：1(3)
  故障值：99 价格：一般
  常见程度（KP允许程度）：常见
  沙色配色的军用手枪民用版，JohnWick的使用利器之一。
  """,
  """\
  FP-45解放者手枪
  年代：1942年
  技能：射击（手枪） 子弹：.45 ACP
  伤害：1D10+2 载弹量：1
  射程：2码 每轮攻击次数：1
  故障值：92 价格：便宜
  常见程度（KP允许程度）：少见
  汽车厂手搓手枪，能打出子弹就是胜利，握把配有几发备用子弹。
  """,
  """\
  HK MK23手枪
  年代：1996年
  技能：射击（手枪） 子弹：.45 ACP
  伤害：1D10+2 载弹量：12
  射程：20码 每轮攻击次数：1(3)
  故障值：99 价格：较贵
  常见程度（KP允许程度）：稀有
  选配有下挂激光和消音器的一支手枪，握把过于厚重，枪身也偏重使得该枪并不怎么受到欢迎。
  """,
  """\
  雷电Thunder .50手枪
  年代：2004年
  技能：射击（手枪） 子弹：.50 BMG
  伤害：2D10+1D8+4 载弹量：1
  射程：20码 每轮攻击次数：1
  故障值：100 价格：昂贵
  常见程度（KP允许程度）：古董
  一款重的发射巴雷特同款.50弹药的手枪，采用闸门装弹，类似于炮弹装填，加上制退器来让射手能够进行操作，多见于CSOL，少女前线游戏中。
  """,
  """\
  CZ75手枪
  年代：1976年
  技能：射击（手枪） 子弹：9mm手枪弹
  伤害：1D10 载弹量：15
  射程：15码 每轮攻击次数：1(3)
  故障值：99 价格：一般
  常见程度（KP允许程度）：常见
  捷克产竞赛级手枪，极为精准的表现加上超高的性价比让军队警察与平民纷纷采购，缺点是扳机较硬，需要适应。
  """,
  """\
  QSZ92式手枪
  年代：1999年
  技能：射击（手枪） 子弹：9mm手枪弹/5.8mm步枪弹
  伤害：1D10/2D6 载弹量：15/20
  射程：15码 每轮攻击次数：1(3)
  故障值：99 价格：一般
  常见程度（KP允许程度）：少见
  国产92式手枪，有两种版本都进行了采纳，一款用于公安，一款用于军队。
  """,
  """\
  S&W M500左轮手枪
  年代：2003年
  技能：射击（手枪） 子弹：.500 S&W Magnum
  伤害：1D10+1D8+1D3 载弹量：5
  射程：20码 每轮攻击次数：1(3)
  故障值：100 价格：较贵
  常见程度（KP允许程度）：少见
  目前批量生产手枪中火力最充沛的一把，可以用于狩猎各类大型生物，必要的时候也可以干人。
  """,
  """\
  马林BFR转轮手枪
  年代：1997年
  技能：射击（手枪） 子弹：.500 S&W Magnum
  伤害：1D10+1D8+1D3 载弹量：5
  射程：20码 每轮攻击次数：1
  故障值：100 价格：较贵
  常见程度（KP允许程度）：少见
  马格南研究所产物，理论上更换弹巢后可以击打任意子弹，单动结构使得它的射速较低。
  """,
  """\
  PfeiferZeliska转轮手枪
  年代：2013年
  技能：射击（手枪） 子弹：.600 Nitro Express
  伤害：3D10+1D8+6 载弹量：5
  射程：30码 每轮攻击次数：1
  故障值：100 价格：奢侈
  常见程度（KP允许程度）：稀有
  目前手枪中火力最充沛的一把，使用的子弹早在1900年即有出现，超高的威力以及难以控制的后坐力让这把枪可以和一些神话生物掰掰手腕。
  """,
  """\
  LeMat转轮手枪
  年代：1856年
  技能：射击（手枪） 子弹：.38 Colt/20号霰弹
  伤害：1D10/ 4D4/2D4/1D4 载弹量：9(1)
  射程：15码 每轮攻击次数：1(3)
  故障值：100 价格：一般
  常见程度（KP允许程度）：少见
  枪口下方附加了一个特殊的霰弹枪管以备不须，9发的弹容量也让火力持续性有了保证，完整装填手枪弹需3回合。
  """,
  """\
  FN HP M1935手枪
  年代：1935年
  技能：射击（手枪） 子弹：9mm手枪弹
  伤害：1D10 载弹量：13
  射程：15码 每轮攻击次数：1(3)
  故障值：99 价格：一般
  常见程度（KP允许程度）：常见
  勃朗宁大威力手枪的第一个生产型，枪身较为沉重。
  """,
  """\
  FN 57手枪
  年代：1998年
  技能：射击（手枪） 子弹：5.7mm穿甲弹
  伤害：1D8(无视5护甲) 载弹量：20
  射程：15码 每轮攻击次数：1(3)
  故障值：99 价格：一般
  常见程度（KP允许程度）：少见
  P90配套手枪，但握把过于厚重以及射击精度的欠缺，让市场反应较为平淡。
  """,
  """\
  杰里科941手枪
  年代：1990年
  技能：射击（手枪） 子弹：9mm手枪弹
  伤害：1D10 载弹量：15
  射程：15码 每轮攻击次数：1(3)
  故障值：99 价格：一般
  常见程度（KP允许程度）：常见
  仿制于CZ75手枪，大量出产于其他国家，重量较重略压手。
  """,
  """\
  S&W M10左轮手枪
  年代：1902年
  技能：射击（手枪） 子弹：.38 Special
  伤害：1D10 载弹量：6
  射程：15码 每轮攻击次数：1(3)
  故障值：100 价格：一般
  常见程度（KP允许程度）：常见
  军警用，俗称点三八，便于携带，但后坐力较大，弹容量较小。
  """,
  """\
  Kel-Tec PMR-30半自动手枪
  年代：2011年
  技能：射击（手枪） 子弹：.22 WMR
  伤害：1D8 载弹量：30
  射程：15码 每轮攻击次数：1(3)
  故障值：96 价格：一般
  常见程度（KP允许程度）：常见
  使用了.22温切斯特马格南子弹的一把手枪，在近距离的数据不亚于9mm手枪弹，但致命缺点是子弹边缘底火结构导致的极易炸膛。
  """,
  """\
  AF2011-A1双管半自动手枪
  年代：2011年
  技能：射击（手枪） 子弹：.45 ACP
  伤害：1D10+2 载弹量：16
  射程：15码 每轮攻击次数：2(6)
  故障值：94 价格：较贵
  常见程度（KP允许程度）：稀有
  意大利阿森纳公司生产的双管手枪，外形参考两只M1911绑在一起，能够在三秒内清空弹匣，但由于双发同时射击的原因，恐怖的后坐力与较高的故障率使得这把玩具更加常见于影视作品中。
  """,
  """\
  Daniel H9 半自动防御手枪
  年代：2024年
  技能：射击（手枪） 子弹：9mm手枪弹
  伤害：1D10+1 载弹量：15
  射程：15码 每轮攻击次数：1(3)
  故障值：92 价格：较贵
  常见程度（KP允许程度）：常见
  美国丹尼尔配件公司生产的新枪，因为频繁出现卡弹（故障）与弹头横置（低精准高伤害）导致该枪曾被召回过，握把较为舒适且枪管略微下移使得它的开枪手感较好，枪口无螺旋结构使得它无法安装制退器或消音器。
  """,
  """\
  日本南部十四式手枪
  年代：1925年
  技能：射击（手枪） 子弹：8mm南部手枪弹
  伤害：1D8 载弹量：8
  射程：15码 每轮攻击次数：1(3)
  故障值：93 价格：一般
  常见程度（KP允许程度）：常见
  日本产手枪，俗称王八盒子，其击锤与弹匣有着致命缺陷导致该手枪极其容易出现走火与卡壳的事故，号称自杀都费劲的手枪。
  """,
  """\
  MBA Gyrojet火箭手枪
  年代：1962年
  技能：射击（手枪） 子弹：12mm火箭弹
  伤害：1D6（近距离）/1D10（远距离） 载弹量：6
  射程：15码 每轮攻击次数：1(3)
  故障值：96 价格：昂贵
  常见程度（KP允许程度）：罕见
  MBA公司生产的火箭手枪，子弹采用火药进行推进，缺点是该手枪在近距离伤害过低，甚至无法击穿瓦楞纸壳，远距离散步又过大，潮湿的环境也会导致该手枪性能大幅下降，最后沦为了古董。
  """,
  """\
  信号枪
  年代：第一次世界大战及以后
  技能：射击（手枪） 子弹：20mm信号弹
  伤害：1D3（燃烧） 载弹量：1
  射程：10码 每轮攻击次数：1
  故障值：100 价格：大众
  常见程度（KP允许程度）：普遍
  从第一次世界大战便出现踪影的信号手枪，无论在哪个时代都可以充当救援用的信号，现代的钢制信号枪可以击出霰弹，但别指望它的射程能有多理想。
  """,
  """\
  犀牛左轮手枪
  年代：2009年
  技能：射击（手枪） 子弹：.357 Magnum
  伤害：1D8+1D4 载弹量：6
  射程：15码 每轮攻击次数：1(3)
  故障值：100 价格：一般
  常见程度（KP允许程度）：常见
  枪管位于下方让感官后坐力较小，但火药燃气可能会造成潜在伤害。
  """
]
"随机手枪弹药" = [
  """\
  特殊弹药：曳光弹
  发射出去的子弹会有一道曳光，为射手提供弹道参考修正弹道。
  但子弹也会暴露射手的位置。

  为下一次的射击提供+10的成功率加成；为敌方的下一次射击提供+5的成功率加成。
  """,
  """\
  特殊弹药：金属被甲弹
  常见的普通子弹，没有任何特殊的加成。
  """,
  """\
  特殊弹药：铅弹
  子弹头采用铅制构造，会让弹头更加容易碎裂，减少跳弹误伤风险。
  但软质子弹头也会减少对目标的伤害。

  使用武器大失败时，误伤队友的概率从100%降低至50%；子弹伤害减少1点。
  """,
  """\
  特殊弹药：空尖弹
  子弹头消除了尖端的部分，使得子弹的扩张力得到了进一步提升。
  但子弹的穿透力也会因此下降，使得该子弹对有甲目标较为匮乏。

  选择其中一项：
  （1）投掷两次伤害并根据目标选择其中一个伤害；有甲：较低伤害，无甲：较高伤害。
  （2）对有甲目标子弹伤害-1，对无甲目标子弹伤害+1D3
  """,
  """\
  特殊弹药：穿甲弹
  子弹头采用更硬更尖锐的材料，使得子弹能够穿过更加坚硬的护甲。
  但因为缺乏停止力的原因，子弹对目标的停止作用有所降低。

  选择其中一项：
  （1）投掷两次伤害，并选取其中较低的那次伤害，无视5点护甲。
  （2）子弹伤害-1D3（伤害最低为1），无视目标5点护甲。
  """,
  """\
  特殊弹药：P弹
  P弹的装药量较大，能够将弹头更加快速的推出枪膛，提高杀伤力。
  但高装药量也意味着，枪械更容易出现毁灭性的故障。

  子弹伤害+1，枪械故障值-3
  """,
  """\
  特殊弹药：RIP弹
  子弹头采用了开花处理，相较于空尖弹而言，子弹的扩张力达到了极致。
  但相应的，即便是面对最为简易的防具，子弹也无法造成有效伤害。

  子弹伤害+1D4，当目标为有甲时，子弹伤害修正为1点。
  """,
  """\
  特殊弹药：AP-S弹
  弹头采用了特殊工艺，使得子弹能够超越常规穿甲弹，撕碎更加有效的护甲。
  但相应的，子弹的停止力也达到了低谷，更不容易打出停止效应。

  无视10点护甲，子弹伤害-1D4（伤害最低为1）。
  """
]